stages:
  - test

.lein:
  image: clojure:lein

test:api:
  extends: .lein
  stage: test
  script:
    - cd api
    - lein deps
    - lein test

test:worker:
  extends: .lein
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375/
  before_script:
    - curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-19.03.1.tgz -o /tmp/docker.tar.gz
    - tar -zxvf /tmp/docker.tar.gz --strip 1 -C /usr/bin
  script:
    - cd worker
    - lein deps
    - lein test
