stages:
  - style
  - linter
  - unit
  - kibit

.lein:
  image: clojure:lein

.lein-api:
  extends: .lein
  before_script:
    - cd api

.lein-worker:
  extends: .lein
  before_script:
    - cd worker

.lein-worker-docker:
  extends: .lein-worker
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375/
  before_script:
    - cd worker
    - curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-19.03.1.tgz -o /tmp/docker.tar.gz
    - tar -zxvf /tmp/docker.tar.gz --strip 1 -C /usr/bin

.lein-style:
  extends: .lein
  stage: style
  script:
    - lein cljfmt check

.lein-linter:
  extends: .lein
  stage: linter
  script:
    - lein eastwood

.lein-unit:
  stage: unit
  script:
    - lein cloverage --junit --output ../target
  artifacts:
    reports:
      junit: target/junit.xml

.lein-kibit:
  extends: .lein
  stage: kibit
  script:
    - lein kibit

style:api:
  extends: 
    - .lein-api
    - .lein-style

style:worker:
  extends: 
    - .lein-worker
    - .lein-style

linter:api:
  stage: linter
  allow_failure: true
  extends:
    - .lein-api
    - .lein-linter
  script:
    - lein eastwood || true

linter:worker:
  stage: linter
  extends:
    - .lein-worker
    - .lein-linter

unit:api:
  extends: 
    - .lein-api
    - .lein-unit

unit:worker:
  extends: 
    - .lein-worker-docker
    - .lein-unit

kibit:api:
  extends: 
    - .lein-api
    - .lein-kibit

kibit:worker:
  extends: 
    - .lein-worker
    - .lein-kibit
