stages:
  - test

.lein:
  stage: test
  image: clojure:lein

.lein-api:
  extends: .lein
  before_script:
    - cd api

.lein-worker:
  extends: .lein
  before_script:
    - cd worker

.lein-worker-docker:
  extends: .lein-worker
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375/
  before_script:
    - cd worker
    - curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-19.03.1.tgz -o /tmp/docker.tar.gz
    - tar -zxvf /tmp/docker.tar.gz --strip 1 -C /usr/bin

.lein-style:
  extends: .lein
  script:
    - lein cljfmt check

.lein-linter:
  extends: .lein
  script:
    - lein eastwood || true

.lein-unit:
  script:
    - lein cloverage --junit --output ../target
  artifacts:
    reports:
      junit: target/junit.xml

.lein-kibit:
  extends: .lein
  script:
    - lein kibit

.hadolint:
  image: hadolint/hadolint:latest-debian
  stage: test

style:api:
  extends: 
    - .lein-api
    - .lein-style

style:worker:
  extends: 
    - .lein-worker
    - .lein-style

linter:api:
  extends:
    - .lein-api
    - .lein-linter

linter:worker:
  extends:
    - .lein-worker
    - .lein-linter

unit:api:
  extends: 
    - .lein-api
    - .lein-unit

unit:worker:
  extends: 
    - .lein-worker-docker
    - .lein-unit

kibit:api:
  extends: 
    - .lein-api
    - .lein-kibit

kibit:worker:
  extends: 
    - .lein-worker
    - .lein-kibit

hadolint:api:
  extends: .hadolint
  script:
    - hadolint api/Dockerfile

hadolint:worker:
  extends: .hadolint
  script:
    - hadolint worker/Dockerfile
