version: '3.1'

services:
  api:
    build:
      context: ./api
    ports:
      - 3000:3000
    restart: on-failure
    depends_on:
      - mongo
    environment:
      MONGO_DATABASE_NAME: schedule
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USER: schedule
      MONGO_AUTH_DB: admin
      MONGO_PASSWORD: "${MONGO_PASSWORD}"

  worker:
    build:
      context: ./worker
    environment:
      DOCKER_DRIVER: overlay2
      MONGO_DATABASE_NAME: schedule
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USER: schedule
      MONGO_AUTH_DB: admin
      MONGO_PASSWORD: "${MONGO_PASSWORD}"
    restart: on-failure
    depends_on:
      - mongo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/ajb:/tmp/ajb

  mongo:
    image: mongo:4.2
    restart: always
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: schedule
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: schedule
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_PASSWORD}"

volumes:
  mongo-data: