name: test

on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: cljfmt
      run: make cljfmt
    - name: lint
      run: make lint
    - name: hadolint
      run: make hadolint
    - name: kibit
      run: make kibit